# Generated by Django 4.2.7 on 2023-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('course', models.IntegerField()),
                ('study_org', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(max_length=255)),
                ('terms', models.BooleanField(default=False)),
            ],
        ),
    ]
