# Generated by Django 4.2.7 on 2023-12-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='terms',
        ),
    ]
